services:

  web:
    build: .
    container_name: cipc_web
    ports:
      - "5000:5000"
    volumes:
      - /home/jurandir/cipc_output:/data
      - /home/jurandir/cipc_rad/config:/config
      - /home/jurandir/cipc_data/cetesb:/data/cetesb
    restart: always
